### ISSUE TITLE
Checkboxes and icons should be aligned

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#10]
On the Lab Screen, the Velocity and Acceleration checkboxes are indented relative to the other checkboxes:
![image](https://user-images.githubusercontent.com/8419308/46564737-93969800-c8c6-11e8-828c-45e03eb6f64a.png)

Velocity and Acceleration checkboxes should be left-aligned with the other checkboxes, and the vector icons should be right-aligned with the line icons in the group above.
![image](https://user-images.githubusercontent.com/8419308/46564777-d35d7f80-c8c6-11e8-8677-c0e07b0ca3e6.png)

**Comment by arouinfar** [comment]
Looks great!

**Comment by arouinfar** [comment]
Oops, forgot to check MAS.

MASB looks perfect, but the top group of checkboxes in MAS are now indented a bit.
![image](https://user-images.githubusercontent.com/8419308/46824111-23b46180-cd4d-11e8-8d48-13d76d1fe01c.png)

**Comment by Denz1994** [comment]
@arouinfar Both sims should be reviewed after the above commit.

**Comment by arouinfar** [comment]
Looks great, thanks @Denz1994!

**Comment by arouinfar** [comment]
For https://github.com/phetsims/QA/issues/220

Looks like this was undone somewhere between dev.9 and dev.10.

dev.9
![image](https://user-images.githubusercontent.com/8419308/48371523-59fd3d80-e679-11e8-9e7d-cd5a4c9071ba.png)

dev.10 and dev.11
![image](https://user-images.githubusercontent.com/8419308/48371773-ead41900-e679-11e8-8bda-fad4e2816078.png)

**Comment by Denz1994** [comment]
Just pushed a fix @arouinfar. Please confirm in master.

**Comment by arouinfar** [comment]
Looks good!
