### ISSUE TITLE
Find alternative color for springNode on Stretch Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#12]
On the Stretch Screen, the springNode is damped. The other screens have zero damping, so to cue that the Stretch Screen is different, the springNode was given a color.
![image](https://user-images.githubusercontent.com/8419308/46624888-49442f80-caef-11e8-89d0-9d6c3a81c1d4.png)

While the purple springNode has good contrast against the other colors in the sim, it is not distinguishable from the gray springNode for those with Protanopia.

<img src="https://user-images.githubusercontent.com/8419308/46591170-2b86b400-ca76-11e8-8dfa-34a54d4c2508.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46591174-32adc200-ca76-11e8-89b0-95b18120964f.png" width=300>

Self-assigning to find an alternative color.

https://github.com/phetsims/masses-and-springs-basics/blob/master/js/stretch/view/StretchScreenView.js#L93

**Comment by arouinfar** [comment]
I tested two other purple options, and both had improved contrast against the gray springNode. Option 2 has just a bit more contrast, so I'd like to go with that @Denz1994. 

## 1
```        
frontColor: new Color('rgb( 197, 112, 162 )'),
middleColor: new Color('rgb( 159, 16, 100 )'),
backColor: new Color('rgb( 79, 8, 50 )')
```

![image](https://user-images.githubusercontent.com/8419308/46623458-f23c5b80-caea-11e8-807d-79b08546e371.png)

<img src="https://user-images.githubusercontent.com/8419308/46623357-9ffb3a80-caea-11e8-95aa-8f1abe3303e1.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46623373-a7badf00-caea-11e8-99ae-d104024d6925.png" width=300>

## 2
```
frontColor: new Color('rgb( 162, 106, 172 )'),
middleColor: new Color('rgb( 100, 6, 117 )'),
backColor: new Color('rgb( 50, 3, 58 )')
```
![image](https://user-images.githubusercontent.com/8419308/46624592-747a4f00-caee-11e8-829f-e29f7f1b7f96.png)

<img src="https://user-images.githubusercontent.com/8419308/46623669-9aeabb00-caeb-11e8-9ebc-4f85ca6c9a2a.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46623676-a2aa5f80-caeb-11e8-9847-039ec02398c0.png" width=300>

**Comment by Denz1994** [comment]
Color selection 2 was applied to the springs on the Stretch screen. Thoughts @arouinfar?

**Comment by arouinfar** [comment]
Looks good! Thanks @Denz1994.
