### ISSUE TITLE
Z-order of springNode incorrect on Stretch screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#13]
Not sure if it's related to #4, but in master, the springNode on the Stretch screen is incorrectly layered. The z-ordering is correct on other screens, however.

![image](https://user-images.githubusercontent.com/8419308/46591408-cdf36700-ca77-11e8-99d8-7abf57c14472.png)

**Comment by Denz1994** [comment]
This is related to #4. The above commit fixed this specific issue, but the larger issue is related to #4.

**Comment by arouinfar** [comment]
@Denz1994 it looks like this got undone in working on #4 or #17.

**Comment by Denz1994** [comment]
Ah, good catch. I just pushed a fix. Master should be reviewed @arouinfar.

**Comment by arouinfar** [comment]
👍
