### ISSUE TITLE
Lab Screen: Move shelf to lower left corner

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#14]
Currently, the shelf position makes things look a bit crowded.

![image](https://user-images.githubusercontent.com/8419308/46629701-068a5380-caff-11e8-8fc3-8e04036a3825.png)

In the mockups, the shelf is in the lower left corner of the screen, which is preferred.

![image](https://user-images.githubusercontent.com/8419308/46629738-291c6c80-caff-11e8-92d2-bd3d60b01d78.png)

**Comment by Denz1994** [comment]
The masses and shelf have been shifted to the lower left side of the Lab screen. Please review in master  @arouinfar.

**Comment by arouinfar** [comment]
Looks like the shelf has moved, but not the masses @Denz1994.
![image](https://user-images.githubusercontent.com/8419308/46752318-18443600-cc7a-11e8-9ea2-c67b0a6429a9.png)

**Comment by Denz1994** [comment]
@arouinfar Could you try pulling again? This may be similar to https://github.com/phetsims/masses-and-springs-basics/issues/5#issuecomment-428050880.

My local copy resembles the lab screen in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.4/phet/masses-and-springs-basics_all_phet.html).

**Comment by arouinfar** [comment]
@Denz1994 I pulled MASB twice before my previous comment. In general, should I also be pulling MAS?

The new shelf position is looking good to me. :)

**Comment by Denz1994** [comment]
Oh, right. Sorry, I should have made that clear. It would be worth pulling MAS and MASB. Closing.
