### ISSUE TITLE
Create screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#15]
Stretch and Lab icons could be adapted from MAS, but it's not clear how best to differentiate between Stretch and Bounce.
<img src="https://user-images.githubusercontent.com/8419308/46630476-831e3180-cb01-11e8-9ee2-f49194d8a68c.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46630434-6d107100-cb01-11e8-92ba-5cfd0f735899.png" width=300>

**Comment by Denz1994** [comment]
Support has been added for home-screen-icons for each screen using placeholders. I have included @arouinfar as the creator for the icons in license.json. This should be reviewed before closing this issue.

At this point, the correct icons can be replaced when ready.

**Comment by arouinfar** [comment]
I've designed these screen icons:
<img src="https://user-images.githubusercontent.com/8419308/46757671-11242480-cc88-11e8-81a0-d20b9fac0f4b.png" width=220>   <img src="https://user-images.githubusercontent.com/8419308/46757669-11242480-cc88-11e8-851c-c5b21650c933.png" width=220>   <img src="https://user-images.githubusercontent.com/8419308/46757670-11242480-cc88-11e8-8c47-926511b69dab.png" width=220>

@Denz1994 here are the asset files:
[stretch_screen_icon.png](https://user-images.githubusercontent.com/8419308/46757751-4df01b80-cc88-11e8-8278-612ff6412c9d.png)
[bounce_screen_icon.png](https://user-images.githubusercontent.com/8419308/46757749-4df01b80-cc88-11e8-9dba-2064a71ac77d.png)
[lab_screen_icon.png](https://user-images.githubusercontent.com/8419308/46757750-4df01b80-cc88-11e8-824f-39a3c3726fe9.png)
[screen_icons.ai](https://drive.google.com/file/d/10C1l7Zjczx6JqMKxogLtOB3xsuHZpAxv/view)

**Comment by Denz1994** [comment]
The above icons look great. I've applied them to the appropriate screens. Please review @arouinfar in master.

**Comment by arouinfar** [comment]
Looks great! Thanks @Denz1994. 

Since screen_icons.ai has been checked in, I'll delete it from Drive.
