### ISSUE TITLE
Should Period Trace be centered about Resting Position?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#16]
In MAS, the Period Trace is centered about the Mass Equilibrium.
![image](https://user-images.githubusercontent.com/8419308/46758898-43835100-cc8b-11e8-9801-c2a7365c9af0.png)

In MASB, the Period Trace is drawn with respect to the center of mass, which looks slightly odd when the resting (equilibrium) position is turned on.
![image](https://user-images.githubusercontent.com/8419308/46758992-775e7680-cc8b-11e8-80d1-dd0f6eab5b32.png)

I realize that the alignment of the Period Trace is somewhat arbitrary, but it might look better if centered on the Resting Position.

@Denz1994 would this be a straightforward change from MAS?

**Comment by Denz1994** [comment]
We can pass in our `basicsVersion` flag and add in some circumstantial logic as a workaround. This seems to work well in both versions, but @arouinfar should confirm.

**Comment by arouinfar** [comment]
Looks awesome, thanks @Denz1994. I definitely prefer this behavior.
