### ISSUE TITLE
Inconsistent Z-ordering of reference lines

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#17]
Across all screens, the lines are inconsistently layered.  In general, I would prefer that the lines are layered above the springNode (for easier measurement), but behind the mass.

On Stretch, both lines are layered behind both the mass and springNode. 
![image](https://user-images.githubusercontent.com/8419308/46760267-d83b7e00-cc8e-11e8-89c6-335f4d43b19b.png)

On Bounce, all lines are behind the mass, but only Resting Position is behind the springNode.
![image](https://user-images.githubusercontent.com/8419308/46760303-f6a17980-cc8e-11e8-9fb6-38314e00bb0b.png)

On Lab, all lines are above the springNode, but the Resting Position is on top of the mass.
![image](https://user-images.githubusercontent.com/8419308/46760431-5566f300-cc8f-11e8-8306-ae9f19f2283a.png) ![image](https://user-images.githubusercontent.com/8419308/46760316-01f4a500-cc8f-11e8-9521-9ea48334fc15.png)

**Comment by Denz1994** [comment]
The order of adding view components to the scene graph has changed. Please review @arouinfar for the above correction.

All lines should be behind the mass and in front of the spring.

**Comment by arouinfar** [comment]
Looks great!
