### ISSUE TITLE
Allow panel/toolbox on right side to expand 50px before scaling down strings 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#18]
Similar to https://github.com/phetsims/masses-and-springs/issues/293

@Denz1994 can you allow the the panels on the right to expand a bit before scaling down the strings? The behavior can match MAS.

Things are looking a bit crowded even for `?stringTest=double`
![image](https://user-images.githubusercontent.com/8419308/46771127-793a3100-ccaf-11e8-9b4f-5e68284b5f56.png)

To keep things looking uniform, the gravity accordion box and toolbox should get wider to match the width of the panel above.

**Comment by Denz1994** [comment]
@arouinfar We adjusted the size of the spring constant panels. Do we still want this pixel expansion, especially on Bounce and Stretch screens?

**Comment by arouinfar** [comment]
Good point @Denz1994. This request was made before the spring constant panels were widened. Things are currently a bit tight:
![image](https://user-images.githubusercontent.com/8419308/47808923-292a1980-dd05-11e8-98af-c97df4ff5350.png)

Rather than expand the panel, could you extend the `maxWidth` so the strings get a bit closer to the icon? Currently, there's quite a bit of dead space between the string and icon.

**Comment by Denz1994** [comment]
The maxWidth has been adjusted to allow for the labels to expand closer to their respective icon. Please review master in MAS and MASB @arouinfar.

**Comment by arouinfar** [comment]
Looks good @Denz1994!
