### ISSUE TITLE
Mystery Mass Values

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#19]
@Denz1994 I'd like to update the mystery mass values to the following:

Stretch & Bounce
* Small: 75 g
* Medium: 100 g
* Large: 200 g

Lab
* Small: 60 g
* Medium: 120 g
* Large: 180 g

**Comment by Denz1994** [comment]
Do you mind if the masses change size? Currently, the masses will look like this when the massValue changes (1.0.0-dev.7). If we keep the sizes the same as they were, I can adjust the density so they visibly keep their size. Thoughts @arouinfar?

**Comment by Denz1994** [comment]
> Also, I imagine you'll switch the string back to a ? once we're finished reviewing the changes, right?
Correct. I left the labels on for testing purposes.

**Comment by Denz1994** [comment]
Can you review master @arouinfar? I will add the `?` when the current state of the masses is satisfactory.

**Comment by arouinfar** [comment]
@Denz1994 the masses all have the correct density, but the values on Lab should be:

> Small: 60 g
Medium: 120 g
Large: 180 g

**Comment by arouinfar** [comment]
Everything looks good @Denz1994!

**Comment by Denz1994** [comment]
Thanks, @arouinfar. The mystery labels have been applied to the mystery masses. Closing.
