### ISSUE TITLE
Change Color of Mystery Masses on Lab Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#20]
Related to #19 

Now that the mystery masses on the Lab no longer match the other screens, the colors should be changed.

Self-assigning to find alternate colors.

**Comment by arouinfar** [comment]
![image](https://user-images.githubusercontent.com/8419308/47047788-d6256380-d155-11e8-9280-eb3440b0aac2.png)

@Denz1994 can you apply these colors to the lab screen?
small: rgb( 10, 198, 157 )
medium: rgb( 9, 19, 174 )
large:  rgb( 195, 51, 115 )

**Comment by Denz1994** [comment]
The lab mass colors have been updated. Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
The Lab screen looks beautiful, but I think you inadvertently applied the change to the small and medium mystery masses on the first two screens.
![image](https://user-images.githubusercontent.com/8419308/47541721-98cc7e80-d897-11e8-9427-c8ab7ab85d02.png)

Stretch and Bounce should look like this:
![image](https://user-images.githubusercontent.com/8419308/47541754-ba2d6a80-d897-11e8-86f1-93dfd6d65a3c.png)

**Comment by Denz1994** [comment]
Great catch. Can you check master now @arouinfar?

**Comment by arouinfar** [comment]
Looks good @Denz1994!
