### ISSUE TITLE
Movable Line should be on top of other lines

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#21]
@Denz1994 I noticed that the z-ordering of the Movable Line could be tweaked a bit.

The Movable Line is currently sandwiched between the Unstretched Lengthand Resting Position, but should be on top of both.
![image](https://user-images.githubusercontent.com/8419308/46981914-7b2d3700-d097-11e8-8013-5d0e73233f09.png)
![image](https://user-images.githubusercontent.com/8419308/46981921-854f3580-d097-11e8-9669-2ab3420895a7.png)

**Comment by Denz1994** [comment]
The above change has been applied. Please review master @arouinfar.

**Comment by arouinfar** [comment]
👍
