### ISSUE TITLE
Add Movable Line to Stretch Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#22]
@Denz1994 can you add the Movable Line to the Stretch Screen? 

Originally, the thought was that the Movable Line was most helpful in dynamic situations, so it was left off of Stretch. However, in working on #19, I found the Movable Line to be pretty helpful in determining the mystery masses, so I think it would be good to include on the Stretch screen too.

**Comment by Denz1994** [comment]
Do you want the checkbox to be added to the LineOptionsNode as well? We can have the movable line always visible on this screen by default as well. Review these dev versions [1.0.0-dev.6](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.6/phet/masses-and-springs-basics_en_phet.html) [1.0.0-dev.7](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.7/phet/masses-and-springs-basics_en_phet.html) and for comparison @arouinfar.

**Comment by arouinfar** [comment]
Thanks @Denz1994! Sorry if I was a bit vague with my original request. I prefer dev.6 (with the checkbox).

**Comment by Denz1994** [comment]
The `movableLineNode` has been added to the Stretch screen and set to visible by default. Master should be reviewed for the above changes @arouinfar.

**Comment by arouinfar** [comment]
@Denz1994 can you set the visibility to off by default?

**Comment by Denz1994** [comment]
I just noticed the movableLineNode isn't visible by default in [1.0.0-dev.6](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.6/phet/masses-and-springs-basics_en_phet.html). Fix incoming...
