### ISSUE TITLE
Add Next-Lab to credits

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#24]
Similar to https://github.com/phetsims/energy-forms-and-changes/issues/50, we should add our collaborators at Next-Lab to the credits.

@Denz1994 please add this to the end of the team section:
and in cooperation with the Next-Lab project

**Comment by Denz1994** [comment]
`and in cooperation with the Next-Lab project` has been added to the team section of the credits. The credits still need to be corrected so I will make a new issue for this.

Leaving to @arouinfar to close.

**Comment by Denz1994** [comment]
Issue #31 has been created for credit changes tracking.

**Comment by arouinfar** [comment]
👍
