### ISSUE TITLE
Make mass slider thumb snappy

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#25]
To create more easily reproducible experiments, we decided that the thumb of the mass slider should snap in increments of 10 g. Tweakers will still adjust the value by 1 g. (This behavior would be similar to the Length and Mass sliders in Pendulum Lab.)

@Denz1994 this would apply to both MAS and MASB.

**Comment by Denz1994** [comment]
An option for `contrainValue` has been applied to the Number Control in `MassValueControlPanel.js`. The slider now snaps by increments of 10 when using the slider and increments of 1 when using the tweakers.

This behavior is applied to both versions of the sim and should be reviewed in master @arouinfar. Reassigning.

**Comment by arouinfar** [comment]
Looks great!!
