### ISSUE TITLE
Change "Spring Stiffness" to "Spring Strength"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#26]
As discussed in today's design meeting, we'd like to change "Spring Stiffness" to "Spring Strength".  Spring Strength still conveys the meaning of spring constant, but avoids potential snickering in middle school classrooms.

**Comment by Denz1994** [comment]
The above change has been applied. @arouinfar Please review master for the above commit.

**Comment by arouinfar** [comment]
👍

**Comment by oliver-phet** [comment]
From phethelp:

> Could you change 'spring strength' to the more correct 'spring stiffness'? Strength is just something else altogether and has a very specific materials science meaning, so I'm not sure how it can convey the idea of stiffness (or if it does, it then has to be un-conveyed later!). Could you call it 'spring constant' and still have it as a qualitative scale?

**Comment by arouinfar** [comment]
@oliver-phet please direct the user to the regular version of Masses and Springs. There, we use the term "Spring Constant". The basics version of the simulation purposefully uses colloquial language as it is intended for a much younger audience. Can you also please share the `screens` query parameter with them? Perhaps they chose to use MASB over MAS because it includes advanced representations like vectors and energy graphs.

**Comment by oliver-phet** [comment]
Replied to user, closing.
