### ISSUE TITLE
Increase size of Mass & Spring Strength panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#27]
In design meeting, the team thought the Mass panel felt a bit small. Since MASB has a bit more open space, we have the room to make the panel a bit larger. For balance, let's also increase the String Strength panels so they maintain the same height as the Mass panel.

@Denz1994 let's start with a 10% increase.

**Comment by Denz1994** [comment]
I've increased the scaling on the MassValueControlPanel and the SpringConstantControlPanel on the Lab Screen. The other screens in both MASB and MAS haven't been adjusted. This is a good point to get feedback from @arouinfar. 

Should we increase the tweaker size on the MassValueControlPanel? What do you think about the thumb size on the sliders? Assigning to @arouinfar for input.

**Comment by arouinfar** [comment]
@Denz1994 the panel is looking pretty big to  me. Can we drop it down to a 5% increase?

I think the relative thumb and tweaker sizes are just fine, so I wouldn't make any adjustments there.

Also, the Spring Strength panel should have the same height as the Mass panel, but it's currently looking a bit off.
![image](https://user-images.githubusercontent.com/8419308/47391144-41cb7b80-d6d6-11e8-825f-b3cb16a7b4c5.png)

**Comment by Denz1994** [comment]
The panels have been adjusted slightly. What do you think about master @arouinfar?

**Comment by arouinfar** [comment]
The bottom alignment looks correct @Denz1994.
![image](https://user-images.githubusercontent.com/8419308/47509529-86205e00-d833-11e8-8802-1c36cd9a5862.png)

The Mass panel looks about the same size as before (bottom), just a bit narrower (top). Did you scale it back to 5% larger than MAS?
![image](https://user-images.githubusercontent.com/8419308/47509643-c41d8200-d833-11e8-8298-f05bfc196ede.png)

**Comment by Denz1994** [comment]
I adjusted the yMargin initially, and that didn't scale the whole component. Instead the maxWidth has been adjusted and the spring strength panel has been adjusted to match as well. Can you check master @arouinfar?

**Comment by arouinfar** [comment]
Looks great! All that's left is the Spring Strength panel heights on the first two screens @Denz1994.

**Comment by Denz1994** [comment]
The panels on the Stretch and Bounce screen have been expanded. Master can now be reviewed @arouinfar.

**Comment by arouinfar** [comment]
Looks good!
