### ISSUE TITLE
Reorganize panel on Lab Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#28]
@Denz1994 please move the Period Trace below the horizontal separator.

<img width="213" alt="screen shot 2018-10-18 at 5 05 04 pm" src="https://user-images.githubusercontent.com/8419308/47189067-060c6c80-d2f8-11e8-96d1-415dd0afbabe.png">

The bottom group of checkboxes will all also turn on the "Center of Oscillation" line (see #29).

**Comment by Denz1994** [comment]
Period trace option removed from LineOptionsNode.js and into VectorVisibilityControlNode.js. Also, the option for `enablePeriodTrace` has been removed from instances of LineOptionsNode.

**Comment by Denz1994** [comment]
This should be reviewed in both basics and non-basics versions @arouinfar. Assigning to you for review.

**Comment by arouinfar** [comment]
Looks good, thanks @Denz1994!
