### ISSUE TITLE
Damping values should be adjusted on each screen to match design doc

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#3]
[Design Doc ](url)states: The springs could have a different color to help cue that they behave differently on Stretch (highly damped) vs. Bounce & Lab (no damping).

Currently the models' damping values don't match this request.

**Comment by Denz1994** [comment]
Adding dev version [1.0.0-dev.2](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.2/phet/masses-and-springs-basics_en_phet.html) here for review.

**Comment by arouinfar** [comment]
@Denz1994 I think we could increase the damping a bit more. Let's try 0.7, since that's the max in MAS.

**Comment by arouinfar** [comment]
Perfect, thanks @Denz1994!
