### ISSUE TITLE
Center Period Trace about Mass Equilibrium

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#30]
In #16 we shifted the Period Trace to be centered about the Resting Position. However, given that we will be adding the Mass Equilibrium (in the form of the Center of Oscillation #29) to the Lab screen, the Period Trace should be shifted back. 

@Denz1994 I think this essentially amounts to undoing the commits for #16.

**Comment by Denz1994** [comment]
The above change has been made to center the period trace around the mass equilibrium. Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
Looks great!
