### ISSUE TITLE
Add Credits

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#31]
This issue should be used to track changes to credits. This should be addressed after dev testing.

**Comment by Denz1994** [comment]
Credits have been updated, awaiting next dev release.

**Comment by Denz1994** [comment]
Adding code-review label, so QA credits are updated if needed.

**Comment by KatieWoe** [comment]
QA so far: Megan Lai, Liam Mulhall, Laura Rea, Jacob Romero, Kathryn Woessner

**Comment by Denz1994** [comment]
@KatieWoe Please check this [RC version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.4/phet/masses-and-springs-basics_en_phet.html) for the updated QA credits.

**Comment by Denz1994** [comment]
Also, @arouinfar could you verify credits as part of #1

**Comment by KatieWoe** [comment]
Looks good for QA

**Comment by Denz1994** [comment]
From slack @KatieWoe said:

> Credits look fine for QA

Removing @KatieWoe assignment. Thanks QA.

**Comment by Denz1994** [comment]
From slack @arouinfar said:

> Credits looks fine to me

Unassigning @arouinfar and closing.
