### ISSUE TITLE
Update Lab screen icon

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#33]
Since the masses on the Lab screen will have different colors (#20), I've updated the icon for the Lab screen. @Denz1994 you can find the updated assets temporarily stored in the MASB design folder:
https://drive.google.com/drive/u/0/folders/1SoF-G10U3el0ctR_9Qb8ncdNY2yvhVco

**Comment by Denz1994** [comment]
The lab icon and assets file has been updated. Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
Looks good! Thanks @Denz1994.
