### ISSUE TITLE
Masses can be dragged behind springNodes and springHangerNode

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#4]
The mass should be the most forward node when dragging. Currently, we can produce this behavior:
![image](https://user-images.githubusercontent.com/13894380/46444199-f1987380-c73e-11e8-8c78-1ac0655b88db.png)

**Comment by Denz1994** [comment]
```js
    // TODO: We are reinitializing this.springNodes. Is this the best way to handle this? Ask JO
    // @public {Array.<OscillatingSpringNode>} Initialize a new array of springNodes with a different color selection.
    this.springNodes = model.springs.map( function( spring ) {
      var springNode = new OscillatingSpringNode(
        spring,
        self.modelViewTransform,
        tandem.createTandem( 'oscillatingSpringNode' ), {
          leftEndLength: -10,
          frontColor: new Color('rgb( 227, 153, 221 )'),
          middleColor: new Color('rgb( 185, 0, 169 )'),
          backColor: new Color('rgb( 93, 0, 85 )')
        }
      );
      self.addChild( springNode );
      return springNode;
    } );
    this.springSystemControlsNode.moveToFront();
```

**Comment by Denz1994** [comment]
The order of adding view components to the scene graph has changed. Please review @arouinfar for the above correction.

 The masses should not be able to be dragged behind the springs or controls.

**Comment by arouinfar** [comment]
@Denz1994 the Stretch and Lab screens look good, but I'm still seeing this on Bounce:
<img width="167" alt="screen shot 2018-10-10 at 3 02 04 pm" src="https://user-images.githubusercontent.com/8419308/46765873-7afaf900-cc9d-11e8-8e4a-435140a130f3.png">

**Comment by Denz1994** [comment]
Just pushed a fix. Review in master @arouinfar?

**Comment by arouinfar** [comment]
👍
