### ISSUE TITLE
Center of Oscillation line appears when not intended

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#41]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Internet Explorer and Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/220
When Resting Position is selected on the lab screen, the Center of Oscillation line appears as well.  The text does not appear, but the line does.  It doesn't occur on the other screens.  According to @arouinfar on Slack the line should only appear when one of the three bottom checkboxes appears.
**Steps to reproduce:**
1. Go to the lab screen
2. Click on Resting Position
3. Put an mass on the spring

**Screenshots:**
![centeron](https://user-images.githubusercontent.com/41024075/48649956-a0240b00-e9b1-11e8-98ee-c4ee6f59e4a1.PNG)

Troubleshooting information (do not edit):

<details>

  
Name: ‪Masses and Springs: Basics‬

URL: https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.11/phet/masses-and-springs-basics_en_phet.html

Version: 1.0.0-dev.11 2018-11-12 16:16:41 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1536x760

Pixel Ratio: 2.5/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"036865d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"9e1987e6","branch":"master"},"dot":{"sha":"bbbd8526","branch":"master"},"griddle":{"sha":"f64a7cf0","branch":"master"},"joist":{"sha":"11f7cf47","branch":"master"},"kite":{"sha":"b0fc6c9c","branch":"master"},"masses-and-springs":{"sha":"0ab4798a","branch":"master"},"masses-and-springs-basics":{"sha":"90423db0","branch":"master"},"phet-core":{"sha":"714b088a","branch":"master"},"phet-io":{"sha":"3acf45ca","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"e90822f4","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"06ed6276","branch":"master"},"scenery":{"sha":"3fbe7bbb","branch":"master"},"scenery-phet":{"sha":"76baf536","branch":"master"},"sherpa":{"sha":"
</details>

**Comment by arouinfar** [comment]
Good catch @KatieWoe! Looks like a bug to me @Denz1994.

**Comment by Denz1994** [comment]
The massEquilibriumLineNode is now conditionally added in basics and non-basics version. A fix was pushed to master and can be tested in next dev release.

**Comment by Denz1994** [comment]
Can you test if this change is acceptable in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.12/phet/masses-and-springs-basics_all_phet.html) @KatieWoe? If all looks good please reassign to me.

**Comment by KatieWoe** [comment]
Looks good.

**Comment by Denz1994** [comment]
Closing this issue.
