### ISSUE TITLE
ResetAllButton touch areas should be expanded

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#45]
This issue was opened to https://github.com/phetsims/QA/issues/220#issuecomment-439101227. This issue will be used for verification from QA in next dev release.

**Comment by Denz1994** [comment]
This commit has affected both MAS and MASB and should be included in the next maintenance release of MAS.

**Comment by Denz1994** [comment]
Can you test if this change is acceptable in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.12/phet/masses-and-springs-basics_all_phet.html) @KatieWoe? If all looks good please reassign to me.

**Comment by Nancy-Salpepi** [comment]
Touch area looks similar to other sims. Closing!
