### ISSUE TITLE
Reset All on Stretch Screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#46]
**Test device:**
Dell and Chromebook
**Operating System:**
Win 10 and ChromeOS
**Browser:**
Chrome and Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/241
Two changes were noted after hitting reset all on the stretch screen.  One major and one minor.  The minor issue is that the ruler moves to a different starting location.  The major issue is that the damping on the springs seems to go away and the screen behaves like bounce.
**Steps to reproduce:**
1. Go to the stretch screen.  If already there reload the page
2. Place a mass on a spring and note behavior
3. Hit reset all
4. Note ruler movement
5. Place a mass on a spring and note new behavior

**Screenshots:**
![resetproblems](https://user-images.githubusercontent.com/41024075/50306975-3e453e00-0454-11e9-987c-e2bd1e25f170.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Masses and Springs: Basics‬
URL: https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.15/phet/masses-and-springs-basics_all_phet.html
Version: 1.0.0-dev.15 2018-12-19 01:22:08 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"69088d35","branch":"master"},"axon":{"sha":"dd291081","branch":"master"},"brand":{"sha":"b2f1706d","branch":"master"},"chipper":{"sha":"e95d808c","branch":"master"},"dot":{"sha":"8d95f26a","branch":"master"},"griddle":{"sha":"d2bdb4c5","branch":"master"},"joist":{"sha":"b91e469a","branch":"master"},"kite":{"sha":"6c78a24f","branch":"master"},"masses-and-springs":{"sha":"5722e440","branch":"master"},"masses-and-springs-basics":{"sha":"76831dae","branch":"master"},"phet-core":{"sha":"9d80d6a8","branch":"master"},"phet-io":{"sha":"8d5f3942","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"a066df33","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b19f6689","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"6f3a9e13","branch":"master"},"phet-io-wrappers":{"sha":"3f730679","branch":"master"},"phetcommon":{"sha":"f8c5396f","branch":"master"},"query-string-machine":{"sha":"96ab0c2b","branch":"master"},"scenery":{"sha":"2cbf350e","branch":"master"},"scenery-phet":{"sha":"18733d78","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"7ac7fca7","branch":"master"},"tambo":{"sha":"e6ea10d9","branch":"master"},"tandem":{"sha":"eb385888","branch":"master"},"twixt":{"sha":"2fb27c38","branch":"master"}}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.  For the ruler, I believe the culprit is that its startup position is incorrect, but resetAll corrects the placement. I've moved that issue to #47.

**Comment by Denz1994** [comment]
The reset listener was setting the `model.dampingProperty` to zero on reset. We want this screen to have non-zero damping. @KatieWoe please confirm this is fixed in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.16/phet/masses-and-springs-basics_en_phet.html).

**Comment by KatieWoe** [comment]
@Denz1994 seems fixed in the linked dev version.

**Comment by Denz1994** [comment]
Nice. I'll close this issue then. The ruler issue will be addressed in #47.
