### ISSUE TITLE
Short Strings are centered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#59]
For https://github.com/phetsims/QA/issues/281
From slack:
> Me:
![centered](https://user-images.githubusercontent.com/41024075/52655673-f3730000-2eb1-11e9-9df9-8199336fd5e4.jpg)
> Are they supposed to be centered like this?
> I feel like this was an issue too
> But I can't find it.

> Amy Rouinfar [10:26 AM]
> No, the padding to the left of the checkbox and to the right of the icons should never change
> Essentially, there would be a big gap between the “x” and the icon.
> Slack Denzell about this one. I don’t remember this issue, specifically.

> Me:
> I just checked, and this is happening in the published version of MAS.

> Denzell Barnett [10:31 AM]
> I don’t recall a specific issue for this checkbox. Checking…
> Hmm not finding any specific issues. Could you create a new issue for this stringTest?

**Comment by arouinfar** [comment]
It looks like the checkbox/icon group is centered in the panel. However, the checkboxes/strings should remain on the left side of the panel, and the icons should remain on the right side of the panel. Making the strings very short should result in a larger gap between the string and icon.

**Comment by Denz1994** [comment]
The fix for the checkbox described above should be applied to all checkbox items. This includes `VectorVisibilityControlNode` and `IndicatorVisibilityControlNode` for both basics and non-basics versions.

**Comment by KatieWoe** [comment]
And the Gravity string seems a bit short @arouinfar 
![longer](https://user-images.githubusercontent.com/41024075/53452122-b2b0d600-39dd-11e9-9230-2db8b32407cc.jpg)

**Comment by arouinfar** [comment]
> And the Gravity string seems a bit short @arouinfar

Thanks @KatieWoe, since this is a maxWidth issue, and not really related to `?stringTest=x`, I've moved https://github.com/phetsims/masses-and-springs-basics/issues/59#issuecomment-467646519 to #63.

**Comment by Denz1994** [comment]
Only vectors panel has been updated with some logic to assign a spacing dynamically, based on the content of the panel. Before I apply these changes elsewhere and continue with refactors, could you please review the behavior of this panel with the arrow vectors on master @arouinfar.

Here is what the vector panel looks like with `stringTest=x`:
![image](https://user-images.githubusercontent.com/13894380/54042965-7299e200-4199-11e9-8c18-49f097a42fa3.png)

**Comment by Denz1994** [comment]
Note that the original panel described in https://github.com/phetsims/masses-and-springs-basics/issues/59#issue-409418640 should be applied to the vector panel as well, so it is safe to review both.

**Comment by arouinfar** [comment]
@Denz1994 the vector panel has the desired alignment with `?stringTest=x`. Ideally, the reference line checkboxes would be left aligned with the vector checkboxes, and the reference line icons would be right-aligned with the vector icons.

Currently, the reference line checkboxes are still centered in master.

**Comment by Denz1994** [comment]
> the vector panel has the desired alignment with ?stringTest=x

Nice. Similar behavior for a dynamic maxWidth was applied to all other checkboxes and radio buttons in with a complimentary icon. Could you review master @arouinfar and assign back to me?

**Comment by arouinfar** [comment]
Looks good in MAS and MASB! Thanks @Denz1994.

**Comment by Denz1994** [comment]
The relevant commits need to be cherry-picked into the RC branch for MASB before the next RC test.

**Comment by Denz1994** [comment]
Relevant commits have been cherry-picked into MAS `masses-and-springs-basics-1.0` branch and MASB `1.0` branch. This is now ready for verification in the next RC test.

**Comment by KatieWoe** [comment]
Looks good in both versions.  MASB 1.0.0-rc.3
