### ISSUE TITLE
[Lab Screen] Movable Line position doesn't reset on ResetAll

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#61]
For https://github.com/phetsims/QA/issues/281

The Movable Line remembers its position, which can be helpful. However, it is not properly resetting when ResetAll is used. This bug is only present on the Lab screen.

To reproduce: 

1. On startup, open Lab.
2. Turn on Movable Line, drag it to the bottom of the screen.
3. Reset all.
4. Turn Movable Line back on, and it will appear at the bottom of the screen, where you last left it.

**Comment by arouinfar** [comment]
I tested master and latest MAS, and the bug is not present there.

**Comment by Denz1994** [comment]
Master has been corrected by adding a listener to the `ResetAllButton`. This commit has been `cherry-picked` into the 1.0 branch as well. I'll leave open for verification for the next RC test.

In the meantime, the fix can be verified in master @arouinfar. Assigning @arouinfar to ensure things are looking good.

**Comment by arouinfar** [comment]
Looks good in master @Denz1994

**Comment by KatieWoe** [comment]
Looks good in both versions.  MASB 1.0.0-rc.3
