### ISSUE TITLE
Gravity maxWidth is too small

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#63]
Discovered by @KatieWoe in https://github.com/phetsims/masses-and-springs-basics/issues/59#issuecomment-467646519 for https://github.com/phetsims/QA/issues/281

The maxWidth of "Gravity" should be much longer, extending almost the whole way across the comboBox. 

@Denz1994 here's a rough mockup showing the desired maxWidth (magenta line).
![image](https://user-images.githubusercontent.com/8419308/53526208-c2452300-3aa0-11e9-9ec6-8b5c6854fc84.png)

**Comment by Denz1994** [comment]
_Note to self_

`GravityAccordionBox` doesn't need the whole model. We should only be passing in the `model.bodyProperty` and the `model.gravityProperty`. I'll make a seperate issue.

**Comment by Denz1994** [comment]
Fix applied in above commit. This should be cherry-picked into master and verified during next RC test.

**Comment by Denz1994** [comment]
Commit has been cherry-picked into the RC branch. Awaiting verification.

**Comment by KatieWoe** [comment]
Looks good in both versions.  1.0.0-rc.3
