### ISSUE TITLE
GravityAccordionBox requires model

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#64]
Comment [here](https://github.com/phetsims/masses-and-springs-basics/issues/63#issuecomment-468684163) sums up initial thoughts.

This will add one more argument to the constructor.

**Comment by Denz1994** [comment]
The commit above cleared things up. This should also be included in the RC branch.

**Comment by Denz1994** [comment]
Fix cherry-picked into the RC branch. Awaiting verification.

**Comment by KatieWoe** [comment]
This looks ok from what I've seen 1.0.0-rc.3.  I hadn't seen this before, so I was a bit confused.  But moving the gravity slider and choosing the different planets doesn't seem to cause any problems.
