### ISSUE TITLE
Resting Position should correspond to Equilibrium Position

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#9]
Currently, the Resting Position is at the center of mass, which would correspond to the Mass Equilibrium in MAS:

![image](https://user-images.githubusercontent.com/8419308/46564691-41557700-c8c6-11e8-986c-dc82e3ec076f.png)

Instead, the Resting Position should correspond to the Equilibrium Position (bottom of springNode):
![image](https://user-images.githubusercontent.com/8419308/46564705-56320a80-c8c6-11e8-9a06-fe1d3356f19b.png)

**Comment by Denz1994** [comment]
The EquilibriumYPositionProperty is used instead of MassEquilibriumYPositionProperty. Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good!
